### PR TITLE
Add CentOS Dojo...

### PR DESCRIPTION
**Pull request by purpleidea**
Add initial event details. Just found out this git repo exists. Other
speakers or event organizer should submit patches.

As an aside, the ./validate.rb script stole all my RAM, made my machine slow, and so ultimately, I couldn't check it, but it's probably fine. Please fix the script :)

### CODE REVIEW

**Comment by garrett** [comment]
I can tell at a glance that your file is incorrect. I've had no issues with the validate script here; it just runs kwalify with some schema and checks the files.

I'll fix the data's syntax. Thanks for the info!

**Comment by garrett** [comment]
BTW: The validate script ran quickly and output:

```
could not find expected ':'
Error: 2015/CentOS-Dojo.yml: line 5, col 1: could not find expected ':' while scanning a simple key
```

(There are more issues, but it doesn't always find them all on the first run.)

**Comment by garrett** [comment]
I fixed the indentation in commit bac6d8a1e2af1230096cd85495c921ca63dc03ad. 

Syntax really is just a technicality; the actual information is the most important part, so thanks again for adding it!

**Comment by purpleidea** [comment]
@garrett hmm.. sorry for any formatting issues... In the future, I'll try and debug the validate.rb issue.

Cheers!

**Pull request merged**
