### PR TITLE
Added OpenStack Hackathon Rio

### PR DESCRIPTION
**Pull request by mary-grace**

### CODE REVIEW

**Comment by bproffitt** [comment]
Looks like this is borking. The Kubecon file seems to be missing? Ping on IRC if you need assistance.

BKP

**Comment by mary-grace** [comment]
ah, I should have renamed the PR. I removed the Kubecon file because I realized it was already included, just under a different name than I anticipated. I'll take a look and see what I can figure out today.

**Comment by bproffitt** [comment]
@mscherer @duck-rh Can you guys look at this? It appears to us that Travis is breaking because it doesn't have the right json gem to run validate.rb.

**Comment by mscherer** [comment]
yeah, that's weerd, when I run locally, it work fine, so I suspect that's something on travis side. That's not a transient issue, as I did restart the build and it fail the same. I did compare a working one and this one, and it do not seems to have obvious reason to fail (besides "some stuff got updated").

**Pull request merged**
