### PR TITLE
Talks in Fosdem by Lalatendu Mohanty and Kaleb KEITHLEY 

### PR DESCRIPTION
**Pull request by LalatenduMohanty**

### CODE REVIEW

**Comment by garrett** [comment]
Thanks!

The distributions devroom hasn't been finalized yet, so I'm still waiting on FOSDEM to update their data. Hopefully these two talks (among others) will show up soon. I'll double-check to ensure the talks are there before finalizing the flyer for print.

FWIW: There are a few outstanding requests that are all waiting on FOSDEM's update data; so you're not alone: https://github.com/OSAS/rh-events/pulls — notable tracks that are not published yet are:

- **Distributions devroom** (emphasis here, as I think there will be a lot of talks, yours included, that will show up as a result of this track)
- Lisp
- Open Document editors devroom
- Open source search devroom
- Perl devroom

...hopefully FOSDEM will add the data in the next day or two.

**Comment by garrett** [comment]
At given points in time, I saw one talk, then both, and then one (a different one from the first one) — do you know if both talks will be happening, or if there's just one talk now?

Right now, the only talk I see with you included is "The CentOS storage SIG and GlusterFS". Is this correct?

**Comment by LalatenduMohanty** [comment]
Yeah, because of the time constraint ( as on Sunday the closing time is early then Saturday) only talk i.e. "The CentOS storage SIG and GlusterFS" is going to happen.

**Comment by garrett** [comment]
Okay, great! Thanks for the quick response. I'll close this pull request now, as it seems resolved.

Thanks again! And see you @ FOSDEM!

**Pull request closed without merging**
